.github/workflows/preview.yaml
README.md
action.yaml
backlogger.py
queries.yaml

The feature needs to be explicitly enabled via a command-line argument. A comment including the priority and a reference to the team website will be added to tickets in the query.
See: https://progress.opensuse.org/issues/113797

Add support for automatic reminder comments

---

backlogger.py

Currently there is no explicit checks on wether a comment was added outside of relying on the update filter. Rely on Redmine's built-in handling of due dates instead.
See: https://progress.opensuse.org/issues/113797#note-15

No reminder comments for exceeded due dates

---

README.md
backlogger.py
queries.yaml
tests/test_comments.py

Feature is used by https://github.com/openSUSE/openqa-tests-backlog/pull/4
Reference: https://progress.opensuse.org/issues/116605

Add support for custom comment message

---

backlogger.py
requirements.txt
tests/test_comments.py
tests/test_output.py

- Use argparse for cleaner handling of switches.
- Remove verbatim printing to stdout that would interfere.
- Output InfluxDB line protocol instead of markdown
See: https://progress.opensuse.org/issues/121582

Support influxdb as an alternate output mode

---

.github/workflows/tests.yaml
backlogger.py
tests/slo.conf
tests/test_output.py

- Escape spaces in tags using backslashes
- Add a simple Telegraf config that reproduces syntax errors
See: https://progress.opensuse.org/issues/121582

Fix InfluxDB output mode and add CI for it

---

backlogger.py

Make sure we get as much issues as we can. The default redmine limit is 25, and the maximum limit one can set is 100.
If we want to make sure we get *all* issues we would have to add paging via 'offset'.
Issue: https://progress.opensuse.org/issues/121582

Increase issue limit to the maximum 100

---

backlogger.py
tests/test_output.py

In order to calculate averages of arbitrary time frames in Grafana, we need the original count and sums.
Issue: https://progress.opensuse.org/issues/121582
I also moved the division by 3600 to the end. The later it is done, the less rounding errors can accumulate.

Add sum of cycleTime and leadTime to influxdb output

---

backlogger.py
tests/test_output.py

For the "Closed yesterday" query we can tell telegraf the exact timestamp for the data.
This way we can execute the telegraf query more often per day to ensure we get data, and also for the other queries there's no need to run this only once a day.
Ticket: https://progress.opensuse.org/issues/121582#note-57
Ideally one would mock `datetime.datetime.today` but I haven't found out how to do that with MagicMock

Add timestamp in nanoseconds for influxdb output

---

backlogger.py

To make the render_influxdb function work also in other projects we need to remove the project part from "api" and "web" data in some cases. For details see [this comment](https://progress.opensuse.org/issues/153205#note-3)

Fix problems with influxdb rendering on projects

---

README.md
backlogger.py
tests/test_output.py

Only return exit code 0 if all queries are good, return exit code 3 if
any query is not OK.
Reference: https://progress.opensuse.org/issues/137828

Enable usage of different exit code when queries not satisfied 

---

action.yaml
foot.html
head.html

Reference: https://progress.opensuse.org/issues/153859

Introduce stable image name with variable query

---

backlogger.py

As described in https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#special-characters this implements proper escaping for every compoment in the influx line protocol output string.
Related to https://progress.opensuse.org/issues/153925

Add proper escaping to influx output

---

backlogger.py
tests/test_output.py

Only counting "In Progress" yields unrealistically low cycle time
values and would not reflect overall time that a common
development ticket is being worked on within a team as often
we use "Feedback" when waiting for others within the team,
e.g. for code review.
This commit counts time in status "Feedback" same as
"In Progress" to account for that.
Related progress issue: https://progress.opensuse.org/issues/155917

Include "Feedback" in cycle time as well

---

backlogger.py

`store_false` will actually turn the switch *off* when used, so the logic was reversed.
Apparently this is broken since b260dbbb0f58a0c2a81583aaf1ac81a6ad3ecca4
Issue: https://progress.opensuse.org/issues/157522

Fix logic for --reminder-comment-on-issues

---

backlogger.py

It was not a bug in Redmine, just a very confusing, non standard API behaviour that lead me to thinking that.
Issue: https://progress.opensuse.org/issues/157858

Remove comment about redmine issue

---

backlogger.py
tests/test_comments.py

The "notes" key might exist but be None
Issue: https://progress.opensuse.org/issues/157858

Handle empty "notes" key

---

.github/workflows/preview.yaml
action.yaml

Switch trigger to pull_request_target and adjust the checkout actions
to run against the latest code in the PR.
Although it works for backlogger, it might impact when the workflow
run in another repository.
https://progress.opensuse.org/issues/158236

Make CI run checkout PR for backlogger_preview

---

README.md

- Use `branches` on `pull_request_target`
- Mention limitations of the preview action
See: https://progress.opensuse.org/issues/158236

Update preview example of the action

---

action.yaml

- Only get the state file we need                                       
- Use a separate folder for the previous state
See: https://progress.opensuse.org/issues/159888

Checkout individual state file to avoid recursion

---

backlogger.py
tests/test_comments.py

This PR adds automatic priority updates once the issues have already a reminder. Not action is taken for Low priority. Code is moved around to avoid redundant API requests. Test code could be also improved but i thought that it wont be a big problem for now.
https://progress.opensuse.org/issues/119176

Provide automatic priority update based on SLO requirements

---

backlogger.py
tests/test_comments.py

https://progress.opensuse.org/issues/119176#note-23

Include link to wiki in the second slo action
